apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vilas-app-1
  namespace: default
spec:
  interval: 15m
  path: "./fluxcd/firstapp/tanmoy-app/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: vilas-app-1
